insert into public.cards(id, name, pack, rarity, element, front_image, power, speed, intelligence, defence, luck) values
('crypto-brooklyn','Brooklyn','CryptoPups','Epic','Wavebyte','/cards/crypto/brooklyn-front.png',85,87,78,80,79),
('crypto-gemstone','Gemstone','CryptoPups','Legendary','Sunpetal','/cards/crypto/gemstone-front.png',82,76,88,81,92),
('crypto-astro','Ace','CryptoPups','Epic','Ghostglitch','/cards/crypto/ace-front.png.jpeg',81,89,85,77,82),
('crypto-bandit','Bandit','CryptoPups','Rare','Nightwind','/cards/crypto/bandit-front.png',88,92,76,84,73),
('crypto-raven','Raven','CryptoPups','Mythic','Dark Nova','/cards/crypto/raven-front.png',91,82,90,84,77),
('cyber-nukie','Nukie','CyberPups','Mythic','Starforge','/cards/cyber/nukie-front.png',78,92,86,74,88),
('cyber-jinx','Jinx','CyberPups','Legendary','Ember Shield','/cards/cyber/jinx-front.png',89,76,83,93,71),
('cyber-elsie','Elsie','CyberPups','Epic','Lunar Circuit','/cards/cyber/elsie-front.png',76,81,84,79,91),
('cyber-metallo','Metallo','CyberPups','Epic','Steel Nova','/cards/cyber/metallo-front.png',91,68,80,94,70),
('cyber-kimiko','Kimiko','CyberPups','Legendary','Candy Nebula','/cards/cyber/kimiko-front.png',82,88,91,76,85),
('alien-aqualis','Aqualis','AlienPups','Rare','Moon Dune','/cards/alien/aqualis-front.png',73,78,71,80,76),
('alien-eclipse-pop','Eclipse Pop','AlienPups','Mythic','Neon Halo','/cards/alien/eclipse-front.png',81,76,92,79,87),
('alien-prism-fang','Prism Fang','AlienPups','Legendary','Aurora Fang','/cards/alien/prismfang-front.png',89,86,83,78,74),
('alien-bloopa','Bloopa','AlienPups','Epic','Bubble Nova','/cards/alien/bloopa-front.png',70,69,88,75,90),
('alien-mintara','Mintara','AlienPups','Rare','Sky Burst','/cards/alien/mintara-front.png',68,74,77,72,85),
('alien-vexa-fang','Vexa Fang','AlienPups','Legendary','Neon Rage','/cards/alien/vexafang-front.png',92,88,84,80,73),
('alien-rosette','Rosette','AlienPups','Epic','Ghost Bloom','/cards/alien/rosette-front.png',76,82,79,71,91),
('alien-blossom-byte','Blossom Byte','AlienPups','Rare','Dream Mist','/cards/alien/blossombyte-front.png',69,78,85,67,92),
('alien-solaro','Solaro','AlienPups','Legendary','Comet Flare','/cards/alien/solaro-front.png',83,87,82,76,79),
('alien-aster','Aster','AlienPups','Epic','Prism Moon','/cards/alien/aster-front.png',75,84,86,70,88),
('alien-nova-umbra','Nova & Umbra','AlienPups','Mythic','Twin Orbit','/cards/alien/nova&umbra-front.png',88,83,90,81,78),
('alien-rosette-spirit-trail','Rosette','AlienPups','Epic','Glow Grove','/cards/alien/rosette-front.png',71,85,80,72,90),
('alien-mintara-nebula-spirit','Mintara','AlienPups','Legendary','Nebula Spirit','/cards/alien/mintara2-front.png',77,74,92,68,89),
('alien-verdix','Verdix','AlienPups','Epic','Sky Sprout','/cards/alien/verdix-front.png',74,79,84,71,87),
('alien-lunabop','Lunabop','AlienPups','Legendary','Moon Pop','/cards/alien/lunabop-front.png',80,82,76,73,91),
('alien-aqualis-coral','Aqualis','AlienPups','Rare','Coral Nebula','/cards/alien/aqualis2-front.png',68,81,79,74,85),
('alien-petalia','Petalia','AlienPups','Epic','Aurora Bloom','/cards/alien/petalia-front.png',72,86,88,69,93),
('alien-cosmabit','Cosmabit','AlienPups','Epic','Cosmic Flame','/cards/alien/cosmobit-front.png',87,91,93,82,79),
('alien-tiko','Tiko','AlienPups','Epic','Starlight Shield','/cards/alien/tiko-front.png',78,92,89,93,74),
('alien-limebyte','Limebyte','AlienPups','Epic','Lunar Ice','/cards/alien/limebyte-front.png',82,91,87,79,74)
on conflict (id) do update set
  name = excluded.name, pack = excluded.pack, rarity = excluded.rarity,
  element = excluded.element, front_image = excluded.front_image,
  power = excluded.power, speed = excluded.speed,
  intelligence = excluded.intelligence, defence = excluded.defence,
  luck = excluded.luck, active = true;

